Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.Neos.TableBuilder: true
    nodeTypes:
      groups:
        table:
          position: 'end'
          label: Table
    userInterface:
      translation:
        autoInclude:
          NeosRulez.Neos.TableBuilder:
            - Main
            - 'NodeTypes/*'
            - 'NodeTypes/Content/*'
            - 'NodeTypes/Component/*'
            - 'NodeTypes/Mixin/*'
